'use strict';
const {PDFDocument,rgb}=PDFLib;
const STORE='exbrayat_chauffage_dossiers_v010', SETTINGS='exbrayat_chauffage_settings_v010';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const CHECKS={
 gaz:['Nettoyage du corps de chauffe et du brûleur','Vérification du circulateur chauffage','Vérification / réglage de la régulation','Vérification des dispositifs de sécurité','Contrôle du conduit de raccordement','VMC gaz : sécurité et conduit','Vérification des débits de gaz','Contrôle de l’embouement','Purge du circuit hydraulique','Contrôle de la pression du circuit','Fonctionnement du circulateur hydraulique','Pression des vases d’expansion','Dimensionnement de la chaudière','Ballon : anodes et accessoires','Vacuité conduits de fumée','Dispositifs extérieurs','Détartrage'],
 fioul:['Démontage et nettoyage du brûleur','Nettoyage du pré-filtre fioul','Nettoyage du filtre de pompe','Nettoyage du corps de chauffe','Sécurités du brûleur','Sécurités de la chaudière','Circulateur de chauffage','Conduit de raccordement','Contrôle de l’embouement','Purge du circuit','Pression du circuit','Circulateur hydraulique','Vases d’expansion','Dimensionnement chaudière','Ramonage conduit de fumée','Ramonage conduit raccordement','Ballon : anodes et accessoires','Amenée d’air / évacuation','Régulation appareil','Régulation installation'],
 granules:['Conduit de raccordement','Vacuité du conduit de fumée','Terminal d’évacuation','Amenées d’air comburant','Ventilateur et éléments aérauliques','Décendrage','Joints et éléments amovibles','Organes de sécurité','Circuit d’alimentation combustible','Connexions électriques','Circulateur','Radiateurs et canalisations','Pression réseau hydraulique','Ramonage conduit de fumée','Vase d’expansion','Vidange pot à boues','Bougie d’allumage']
};
const FIELD_MAP={
 gaz:{template:'templates/attestation-gaz.pdf',prefix:'A2-',fields:{contrat:'N° DU CONTRAT',entreprise:'Coordonnees prestataire',client:'Coordonnees client',adresse:'Adresse installation',local:'Local chaudiere',marque:'marque1',puissance:'puissance1',evacuation:'type1',miseService:'mes1',serie:'ns1',dernierEntretien:'Date entretien',dernierRamonage:'Date ramonage',bruleurMarque:'marque2',bruleurPuissance:'puissance2',bruleurDate:'mes2',bruleurSerie:'ns2',tempFumees:'Temp fumees',tempAmbiante:'Temp ambiante',co2:'Teneur co2',o2:'Teneur o2',co:'Teneur co',appareilMesure:'Appareil mesure',rendement:'Rendement1',defauts:'Defauts corriges',usage:'Usage',ameliorations:'Ameliorations',remplacement:'Remplacement',ville:'Fait a',dateVisite:'Fait le',dateVisite2:'Date visite'},groups:17},
 fioul:{template:'templates/attestation-fioul.pdf',prefix:'A2-',fields:{contrat:'N° DU CONTRAT',entreprise:'Coordonnees prestataire',client:'Coordonnees client',adresse:'Adresse installation',local:'Local chaudiere',marque:'marque1',puissance:'puissance1',evacuation:'type1',miseService:'mes1',serie:'ns1',dernierEntretien:'Date entretien',dernierRamonage:'Date ramonage',bruleurMarque:'marque2',bruleurPuissance:'puissance2',bruleurDate:'mes2',gicleur:'gicleur',bruleurSerie:'ns2',tempFumees:'Temp fumees',tempAmbiante:'Temp ambiante',co2:'Teneur co2',o2:'Teneur o2',pressionGicleur:'Pression gicleur',co:'Teneur co',appareilMesure:'Marque et rélérence',rendement:'Rendement1',defauts:'Defauts corriges',usage:'Usage',ameliorations:'Ameliorations',remplacement:'Remplacement',ville:'Fait a',dateVisite:'Fait le',dateVisite2:'Date visite'},groups:20},
 granules:{template:'templates/attestation-granules.pdf',prefix:'A2-',fields:{contrat:'N° DU CONTRAT',entreprise:'Coordonnees prestataire',client:'Coordonnees client',adresse:'Adresse installation',local:'Local chaudiere',marque:'marque1',puissance:'puissance1',evacuation:'type1',miseService:'mes1',serie:'ns1',dernierEntretien:'Date entretien',dernierRamonage:'Date ramonage',co:'Teneur co',appareilMesure:'Appareil mesure',defauts:'Defauts corriges',usage:'Usage',ameliorations:'Ameliorations',remplacement:'Remplacement',ville:'Fait a',dateVisite:'Fait le',dateVisite2:'Date visite'},groups:17}
};
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function defaults(){return {entrepriseNom:'SARL EXBRAYAT CEDRIC PLOMBERIE CHAUFFAGE',entrepriseAdresse:'26 avenue de Jumeaux\n63570 BRASSAC-LES-MINES',entrepriseTel:'06 17 16 15 38',entrepriseEmail:'cedric.exbrayat@orange.fr',technicien:'EXBRAYAT Cédric'}}
function settings(){try{return {...defaults(),...JSON.parse(localStorage.getItem(SETTINGS)||'{}')}}catch{return defaults()}}
function renderSettings(){const s=settings();Object.keys(s).forEach(k=>{const e=$('#'+k);if(e)e.value=s[k]})}
function switchPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));scrollTo(0,0)}
$$('nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));
$$('.modules button[data-type]').forEach(b=>b.onclick=()=>{type.value=b.dataset.type;updateType();switchPage('entretien')});
function updateType(){const t=type.value;$('#moduleTitle').textContent={gaz:'Entretien chaudière gaz',fioul:'Entretien chaudière fioul',granules:'Entretien poêle / chaudière granulés'}[t];$('#burnerCard').style.display=t==='fioul'||t==='gaz'?'block':'none';$('#gicleurPression').style.display=t==='fioul'?'flex':'none';$('#tirageField').style.display=t==='granules'?'flex':'none';$('#excesField').style.display=t==='granules'?'flex':'none';renderChecks(t)}
function renderChecks(t,values=[]){const box=$('#checks');box.innerHTML='';CHECKS[t].forEach((label,i)=>{const row=document.createElement('div');row.className='check-row';row.innerHTML=`<span>${i+1}. ${label}</span><select name="check${i+1}"><option>Oui</option><option>Non</option><option>Sans objet</option></select>`;row.querySelector('select').value=values[i]||'Oui';box.appendChild(row)})}
type.onchange=updateType;
function setupCanvas(id){const c=$('#'+id),ctx=c.getContext('2d');let down=false;function resize(){const r=c.getBoundingClientRect(),d=devicePixelRatio||1,old=c.toDataURL();c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);ctx.lineWidth=2;ctx.lineCap='round';const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,r.width,r.height);im.src=old}resize();addEventListener('resize',resize);function pos(e){const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return [p.clientX-r.left,p.clientY-r.top]}c.addEventListener('pointerdown',e=>{down=true;ctx.beginPath();ctx.moveTo(...pos(e));c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!down)return;ctx.lineTo(...pos(e));ctx.stroke()});c.addEventListener('pointerup',()=>down=false);return c}
setupCanvas('sigTech');setupCanvas('sigClient');$$('[data-clear]').forEach(b=>b.onclick=()=>{const c=$('#'+b.dataset.clear);c.getContext('2d').clearRect(0,0,c.width,c.height)});
function data(){const o=Object.fromEntries(new FormData($('#form')).entries());o.checks=CHECKS[o.type].map((_,i)=>o['check'+(i+1)]||'Oui');o.sigTech=$('#sigTech').toDataURL('image/png');o.sigClient=$('#sigClient').toDataURL('image/png');o.id=o.id||`${Date.now()}`;o.savedAt=new Date().toISOString();return o}
function save(){if(!$('#form').reportValidity())return;const d=data(),list=load();const i=list.findIndex(x=>x.id===d.id);i>=0?list[i]=d:list.unshift(d);localStorage.setItem(STORE,JSON.stringify(list));$('#form').dataset.id=d.id;renderHistory();toast('Entretien enregistré')}
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return []}}
function renderHistory(){const q=($('#search').value||'').toLowerCase(),box=$('#history');box.innerHTML='';load().filter(d=>`${d.clientNom} ${d.ville} ${d.type}`.toLowerCase().includes(q)).forEach(d=>{const r=document.createElement('div');r.className='history-item';r.innerHTML=`<div><strong>${d.clientNom||'Sans nom'}</strong><div>${d.ville||''} — ${d.type} — ${d.dateVisite||''}</div></div><div><button>Ouvrir</button> <button>Supprimer</button></div>`;const [a,b]=r.querySelectorAll('button');a.onclick=()=>fill(d);b.onclick=()=>{if(confirm('Supprimer cet entretien ?')){localStorage.setItem(STORE,JSON.stringify(load().filter(x=>x.id!==d.id)));renderHistory()}};box.appendChild(r)});if(!box.children.length)box.innerHTML='<p class="hint">Aucun entretien enregistré.</p>'}
function fill(d){$('#form').reset();type.value=d.type||'gaz';updateType();Object.entries(d).forEach(([k,v])=>{const e=$('#form').elements[k];if(e&&typeof v==='string')e.value=v});renderChecks(d.type,d.checks);$('#form').dataset.id=d.id;drawSaved('sigTech',d.sigTech);drawSaved('sigClient',d.sigClient);switchPage('entretien')}
function drawSaved(id,url){const c=$('#'+id),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!url)return;const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,c.clientWidth,c.clientHeight);im.src=url}
function newForm(){if(!confirm('Créer une nouvelle fiche ?'))return;$('#form').reset();delete $('#form').dataset.id;type.value='gaz';$('[name=dateVisite]').value=new Date().toISOString().slice(0,10);updateType();$$('canvas').forEach(c=>c.getContext('2d').clearRect(0,0,c.width,c.height))}
$('#saveBtn').onclick=save;$('#newBtn').onclick=newForm;$('#search').oninput=renderHistory;
$('#saveSettings').onclick=()=>{const s={};Object.keys(defaults()).forEach(k=>s[k]=$('#'+k).value);localStorage.setItem(SETTINGS,JSON.stringify(s));toast('Coordonnées enregistrées')};
function safeText(form,name,value){if(value===undefined||value===null||value==='')return;try{form.getTextField(name).setText(String(value))}catch(e){console.debug('Champ absent',name)}}
function safeSelect(form,name,value){try{form.getRadioGroup(name).select(value)}catch(e){try{form.getDropdown(name).select(value)}catch(_){console.debug('Groupe absent',name,value)}}}
function companyText(){const s=settings();return [s.entrepriseNom,s.entrepriseAdresse,`Tél : ${s.entrepriseTel}`,s.entrepriseEmail].filter(Boolean).join('\n')}
function clientText(d){return [d.clientNom,d.clientTel].filter(Boolean).join('\n')}
function formatDate(v){if(!v)return '';const p=v.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v}
async function createPdf(){if(!$('#form').reportValidity())return;save();const d=data(),cfg=FIELD_MAP[d.type],bytes=await fetch(cfg.template).then(r=>r.arrayBuffer()),doc=await PDFDocument.load(bytes),formPdf=doc.getForm(),f=cfg.fields;
 const vals={contrat:d.contrat,entreprise:companyText(),client:clientText(d),adresse:d.adresse,local:d.local,marque:d.marque,puissance:d.puissance,evacuation:d.evacuation,miseService:d.miseService,serie:d.serie,dernierEntretien:d.dernierEntretien,dernierRamonage:d.dernierRamonage,bruleurMarque:d.bruleurMarque,bruleurPuissance:d.bruleurPuissance,bruleurDate:d.bruleurDate,gicleur:d.gicleur,bruleurSerie:d.bruleurSerie,tempFumees:d.tempFumees,tempAmbiante:d.tempAmbiante,co2:d.co2,o2:d.o2,pressionGicleur:d.pressionGicleur,co:d.co,appareilMesure:d.appareilMesure,rendement:d.rendement,defauts:d.defauts,usage:d.usage,ameliorations:d.ameliorations,remplacement:d.remplacement,ville:d.ville,dateVisite:formatDate(d.dateVisite),dateVisite2:formatDate(d.dateVisite)};
 Object.entries(vals).forEach(([k,v])=>{if(f[k])safeText(formPdf,cfg.prefix+f[k],v)});
 d.checks.forEach((v,i)=>safeSelect(formPdf,`${cfg.prefix}Groupe${i+1}`,v));
 try{formPdf.flatten()}catch(e){console.warn(e)}
 const logoBytes=await fetch('logo-exbrayat.png').then(r=>r.arrayBuffer()),logo=await doc.embedPng(logoBytes),p0=doc.getPages()[0],ps=p0.getSize();p0.drawImage(logo,{x:ps.width-125,y:ps.height-62,width:105,height:45,opacity:.92});
 const last=doc.getPages()[doc.getPageCount()-1],sz=last.getSize();async function sig(url,x){if(!url||url.length<100)return;const png=await doc.embedPng(await fetch(url).then(r=>r.arrayBuffer()));last.drawImage(png,{x,y:35,width:155,height:70})}
 const y=d.type==='gaz'?42:35; if(d.sigTech) {const png=await doc.embedPng(await fetch(d.sigTech).then(r=>r.arrayBuffer()));last.drawImage(png,{x:75,y,width:155,height:70})} if(d.sigClient){const png=await doc.embedPng(await fetch(d.sigClient).then(r=>r.arrayBuffer()));last.drawImage(png,{x:330,y,width:155,height:70})}
 const out=await doc.save();const blob=new Blob([out],{type:'application/pdf'}),url=URL.createObjectURL(blob),name=`ATTESTATION-${d.type.toUpperCase()}-${(d.clientNom||'CLIENT').replace(/[^a-z0-9]/gi,'_')}-${d.dateVisite||''}.pdf`;if(navigator.share&&navigator.canShare){try{const file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare({files:[file]})){await navigator.share({files:[file],title:name});return}}catch(e){}}
 const w=window.open(url,'_blank');if(!w){const a=document.createElement('a');a.href=url;a.download=name;a.click()}setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('#pdfBtn').onclick=()=>createPdf().catch(e=>{console.error(e);alert('Erreur pendant la création du PDF : '+e.message)});
renderSettings();renderHistory();$('[name=dateVisite]').value=new Date().toISOString().slice(0,10);updateType();if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
